[package]
name = "rmfeeder"
version = "0.1.0"
edition = "2024"

[dependencies]
epub-builder = "0.8.0"
feed-rs = "2.3.1"
html5ever = "0.36.1"
markup5ever_rcdom = "0.36.0"
serde = "1.0.228"
serde_json = "1.0.145"
